[2025-02-06T15:17:53.121+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T15:17:53.140+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_training_dag.task_read_data scheduled__2025-01-01T00:22:00+00:00 [queued]>
[2025-02-06T15:17:53.154+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_training_dag.task_read_data scheduled__2025-01-01T00:22:00+00:00 [queued]>
[2025-02-06T15:17:53.155+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T15:17:53.201+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): task_read_data> on 2025-01-01 00:22:00+00:00
[2025-02-06T15:17:53.210+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_training_dag', 'task_read_data', 'scheduled__2025-01-01T00:22:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/training_dag.py', '--cfg-path', '/tmp/tmpd60d3vi_']
[2025-02-06T15:17:53.211+0000] {standard_task_runner.py:105} INFO - Job 135: Subtask task_read_data
[2025-02-06T15:17:53.213+0000] {logging_mixin.py:190} WARNING - /opt/conda/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1027) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-06T15:17:53.214+0000] {standard_task_runner.py:72} INFO - Started process 1060 to run task
[2025-02-06T15:17:53.290+0000] {task_command.py:467} INFO - Running <TaskInstance: my_training_dag.task_read_data scheduled__2025-01-01T00:22:00+00:00 [running]> on host b98e1e481464
[2025-02-06T15:17:53.504+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_training_dag' AIRFLOW_CTX_TASK_ID='task_read_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:22:00+00:00'
[2025-02-06T15:17:53.506+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T15:17:53.508+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T15:17:53.510+0000] {logging_mixin.py:190} INFO - Current task name:task_read_data state:running start_date:2025-02-06 15:17:53.141233+00:00
[2025-02-06T15:17:53.511+0000] {logging_mixin.py:190} INFO - Dag name:my_training_dag and current dag run status:running
[2025-02-06T15:17:53.512+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T15:17:53.513+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-06T15:17:53.669+0000] {python.py:240} INFO - Done. Returned value was: task_train_model
[2025-02-06T15:17:53.671+0000] {branch.py:38} INFO - Branch into task_train_model
[2025-02-06T15:17:53.673+0000] {skipmixin.py:230} INFO - Following branch ('task_train_model',)
[2025-02-06T15:17:53.691+0000] {skipmixin.py:278} INFO - Skipping tasks []
[2025-02-06T15:17:53.788+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T15:17:53.788+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_training_dag, task_id=task_read_data, run_id=scheduled__2025-01-01T00:22:00+00:00, execution_date=20250101T002200, start_date=20250206T151753, end_date=20250206T151753
[2025-02-06T15:17:53.831+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-06T15:17:53.832+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-06T15:17:53.833+0000] {logging_mixin.py:190} INFO - Dag name:my_training_dag queued_at:2025-02-06 15:17:25.201577+00:00
[2025-02-06T15:17:53.834+0000] {logging_mixin.py:190} INFO - Task hostname:b98e1e481464 operator:BranchPythonOperator
[2025-02-06T15:17:53.872+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T15:17:53.910+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-06T15:17:53.921+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-06T15:18:06.718+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T15:18:06.730+0000] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: my_training_dag.task_read_data scheduled__2025-01-01T00:22:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-02-06T15:18:06.738+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
