[2025-02-06T09:00:30.644+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T09:00:30.662+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T01:27:00+00:00 [queued]>
[2025-02-06T09:00:30.675+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T01:27:00+00:00 [queued]>
[2025-02-06T09:00:30.676+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 1
[2025-02-06T09:00:30.714+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): task_random_choice> on 2025-01-01 01:27:00+00:00
[2025-02-06T09:00:30.717+0000] {standard_task_runner.py:72} INFO - Started process 51 to run task
[2025-02-06T09:00:30.719+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'task_random_choice', 'scheduled__2025-01-01T01:27:00+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpisuc9yaa']
[2025-02-06T09:00:30.720+0000] {standard_task_runner.py:105} INFO - Job 312: Subtask task_random_choice
[2025-02-06T09:00:30.801+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag.task_random_choice scheduled__2025-01-01T01:27:00+00:00 [running]> on host 56ad8bb1b89a
[2025-02-06T09:00:30.912+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='task_random_choice' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T01:27:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T01:27:00+00:00'
[2025-02-06T09:00:30.914+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T09:00:30.914+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T09:00:30.915+0000] {logging_mixin.py:190} INFO - Current task name:task_random_choice state:running start_date:2025-02-06 09:00:30.663166+00:00
[2025-02-06T09:00:30.915+0000] {logging_mixin.py:190} INFO - Dag name:my_first_dag and current dag run status:running
[2025-02-06T09:00:30.916+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T09:00:30.916+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-02-06T09:00:30.917+0000] {python.py:240} INFO - Done. Returned value was: task_1
[2025-02-06T09:00:30.917+0000] {branch.py:38} INFO - Branch into task_1
[2025-02-06T09:00:30.918+0000] {skipmixin.py:230} INFO - Following branch ('task_1',)
[2025-02-06T09:00:30.929+0000] {skipmixin.py:278} INFO - Skipping tasks []
[2025-02-06T09:00:30.985+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T09:00:30.985+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=task_random_choice, run_id=scheduled__2025-01-01T01:27:00+00:00, execution_date=20250101T012700, start_date=20250206T090030, end_date=20250206T090030
[2025-02-06T09:00:31.025+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-06T09:00:31.026+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-06T09:00:31.027+0000] {logging_mixin.py:190} INFO - Dag name:my_first_dag queued_at:2025-02-06 08:59:22.616772+00:00
[2025-02-06T09:00:31.027+0000] {logging_mixin.py:190} INFO - Task hostname:56ad8bb1b89a operator:BranchPythonOperator
[2025-02-06T09:00:31.053+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T09:00:31.087+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-06T09:00:31.098+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
