[2025-02-06T13:34:30.090+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-06T13:34:30.110+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_training_dag.task_insert_data scheduled__2025-01-01T02:22:00+00:00 [queued]>
[2025-02-06T13:34:30.127+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_training_dag.task_insert_data scheduled__2025-01-01T02:22:00+00:00 [queued]>
[2025-02-06T13:34:30.129+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-06T13:34:30.167+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): task_insert_data> on 2025-01-01 02:22:00+00:00
[2025-02-06T13:34:30.175+0000] {standard_task_runner.py:72} INFO - Started process 247 to run task
[2025-02-06T13:34:30.178+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_training_dag', 'task_insert_data', 'scheduled__2025-01-01T02:22:00+00:00', '--job-id', '3373', '--raw', '--subdir', 'DAGS_FOLDER/training_dag.py', '--cfg-path', '/tmp/tmp0zm7j1mj']
[2025-02-06T13:34:30.179+0000] {standard_task_runner.py:105} INFO - Job 3373: Subtask task_insert_data
[2025-02-06T13:34:30.411+0000] {task_command.py:467} INFO - Running <TaskInstance: my_training_dag.task_insert_data scheduled__2025-01-01T02:22:00+00:00 [running]> on host 280e83a6ee46
[2025-02-06T13:34:30.597+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_training_dag' AIRFLOW_CTX_TASK_ID='task_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T02:22:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T02:22:00+00:00'
[2025-02-06T13:34:30.599+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-06T13:34:30.600+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-06T13:34:30.600+0000] {logging_mixin.py:190} INFO - Current task name:task_insert_data state:running start_date:2025-02-06 13:34:30.111238+00:00
[2025-02-06T13:34:30.601+0000] {logging_mixin.py:190} INFO - Dag name:my_training_dag and current dag run status:running
[2025-02-06T13:34:30.602+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-06T13:34:30.632+0000] {logging_mixin.py:190} INFO - Table : 'iris_data'  created succesfully
[2025-02-06T13:34:30.737+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-06T13:34:30.756+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-06T13:34:30.757+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_training_dag, task_id=task_insert_data, run_id=scheduled__2025-01-01T02:22:00+00:00, execution_date=20250101T022200, start_date=20250206T133430, end_date=20250206T133430
[2025-02-06T13:34:30.801+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-02-06T13:34:30.802+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-02-06T13:34:30.803+0000] {logging_mixin.py:190} INFO - Dag name:my_training_dag queued_at:2025-02-06 13:34:26.163483+00:00
[2025-02-06T13:34:30.803+0000] {logging_mixin.py:190} INFO - Task hostname:280e83a6ee46 operator:PythonOperator
[2025-02-06T13:34:30.835+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-06T13:34:30.877+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-06T13:34:30.889+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
